transform.js

This change makes it possible to specify sheetify transforms
across your package through browserify transform arguments, e.g.
{
"browserify": {
"transform": [
["sheetify", { "use": ["sheetify-cssnext"] }]
]
}
}
Thanks! :)

Allow specifying transforms through package.json

---

README.md

I wasn't sure what the `:host` pseudo-selector was for until I dug through the closed issues.  Googling it brings up the shadow DOM and styling _it's_ root element but my brain was all "I'm not using the shadow DOM, maybe that's what this for? IDK".
Then I just played with it in the code and generated a page and realized it was exactly what I was looking for.  An example of the transformed CSS would go a long way to showing how that is uses.

Make it clearer what `:host` does

---

index.js
transform.js

This pull request will fix #72 
Also noticed that there was no error handling for when `falafel` was being run. So essentially for the end user using `sheetify` with `budo` if you made a JS syntax error it would halt `budo`.

Error handling for postcss.process and running falafel fails

---

index.js

I found a situation where
```js
var prefix = sf`
:host {}
`
```
resulted in different prefixes when generated in node & later generated using browserify & the sheetify transform.
Somehow the prefix created with node had whitespace (the newline after the `sf` call) that wasn't present in the prefix created with browserify & the transform.
This is a quick fix to ensure there's no extra whitespace around the `src`.

Trim `src` to avoid string padding errors

---

package.json

As per https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/ closes #68. Thanks!
cc/ @ahdinosaur @hughsk

deps: fix peerdep in v3

---

test/fixtures/example.json
test/json.js
transform.js

before this commit, `require`-ing a JSON file causes
```
SyntaxError: Unexpected token ...
```
this commit
- adds a test for this situation, and
- checks filenames coming in and passes `.json` files through without transformation.
(`through2` without arguments creates a pass-through stream)
copypasta from: https://github.com/yoshuawuyts/es2020/pull/13

pass JSON files through

---

transform.js

You'll see I didn't add a test because I thought it was simply too much work to do for a minor change (with this simple change we should check that a modification in a CSS file updates the bundle just fine). I just can confirm watch mode works now from my own manual tests in the browser.

emit file event on imports. Fix #55

---

package.json

continuation of https://github.com/stackcss/sheetify/issues/77. without this, tests are still using old version of `css-extract` before https://github.com/stackcss/css-extract/pull/6.

test: upgrade css-extract

---

index.js
package.json
test/prefix.js

This fixes prefix generation when running sheetify from within node without using a browserify transform on the JS.  Prior to this fix, calling sheetify would generate hashes from module names and file paths which isn't ever a correct prefix.  
This is useful for when generating external css files for use in an electron app with unbundled JS code where you don't have access to the corrected transform output.

Fix prefix calculation from node

---

README.md

Simplifies the docs a little; less odd `vdom` stuff and a bit more to the point - also renamed variables to `html` and `css` so we can get syntax highlighting in. Figure this is good so just gonna merge :grin:

chore(docs): simplify syntax

---

test/fixtures/plugins-expected.css
test/fixtures/plugins-source.js
test/plugins.js
transform.js

This patch allows the following code to work:
```js
var foo = {}
foo.bar = css`.foo { color: blue }`
```

fix object assignments

---

package.json
transform.js

Background: substack/node-browserify#1667
~~Also depends on substack/node-falafel#62 for full async/await support~~ (merged)

Upgrade falafel to ^2.1.0, use ecmaVersion 8

---

test/fixtures/transform-package/package.json
test/transform-package.js

Just some minor changes removing unnecessary options. I guess it's up to you whether you want these changes, but I think it's best to keep things minimal!

Remove unnecessary options from transform-package tests

---

index.js
package.json
test/fixtures/simple-plugin.js
test/plugins.js
transform.js

This makes it possible to pass options to sheetify plugins using
the browserify subarg syntax on the cli:
```bash
browserify -t [ sheetify -t [ sheetify-sass --indentedSyntax ] ]
```

feat(transform): support subarg syntax in transform, closes #140

---

transform.js

Allows us to track imported files through `css('./file-name.css')`. Thanks!
- https://github.com/stackcss/sheetify/issues/144
- https://github.com/choojs/bankai/issues/386

watch file imports

---

index.js
test/fixtures/files-plugin.js
test/plugins.js
transform.js

`'file'` events will be emitted for each file listed in `files`.
This allows watchify et al to pick up on files that were included by sheetify transforms.

Allow transforms to return a `{ css, files }` object

---

package.json

For some reason sheetify-cssnext@1 stopped working at some point, but
it's all good again in v2.

Fix test by upgrading sheetify-cssnext

---

package.json
transform.js

This patch switches to transform-ast, which has an almost identical API to falafel but also generates source maps. transform-ast has a `.walk()` method that we can use to avoid having to parse the source twice just to walk it twice, so this should speed things up a bit too!

Source maps! closes #62

---

package.json
transform.js

https://github.com/Rich-Harris/buble/pull/67 changed Bublé template strings to compile similarly to Babel ones, for spec reasons.
With this patch, the new style as well as the old style are detected correctly.

Handle new Bublé template string compilation.

---

README.md

I update the README because bel is now called [nanohtml](https://github.com/choojs/nanohtml)

rename bel to nanohtml

---

package.json

It's a big dependency (it pulls in a full npm cli install for example) and it seems like something that should be installed globally instead. It's not used by any scripts.

Remove npm-check-updates

---

index.js
test/plugins.js

Makes these equivalent:
```js
b.transform(sheetify, {
transform: ['sheetify-cssnext']
})
```
```js
b.transform(sheetify, {
transform: [require('sheetify-cssnext')]
})
```
Previously, the latter would throw an error.

Allow specifying transforms as functions
